spring:
  application:
    name: minidorray_gateway
  messages:
    basename: message
    encoding: UTF-8
  data:
    redis:
      host: 133.186.241.167
      port: 6379
      password: "*N2vya7H@muDTwdNMR!"
      database: 18
